### ISSUE TITLE
How to increase height of toolbar?

### ISSUE THREAD

**Issue by hmelder** [msorvig/qt-macos-examples#2]
Hi,
Thank you for the great examples!
Is there a way to increase the vertical spacing of the toolbar in the accessoryview example?

**Comment by msorvig** [comment]
Hello! Great to hear that they are useful.

I think the vertical size is fixed for the left/right accessory views. See https://github.com/robin/TitlebarAndToolbar, which has ha good overview of the options.

**Comment by hmelder** [comment]
But iTunes has a larger toolbar. Is this due to the larger cocoa widgets used in the accessory view? Apple's Cocoa Documentation doesn't help either.
